### ISSUE TITLE
Crash on batch export of Pokémon Violet trpfs on v1.2.0

### ISSUE THREAD

**Issue by melsbacksfriend** [pkZukan/gftool#12]
IDK why it happens with Violet and not Scarlet but here's the error I get: 
![Screenshot 2023-03-14 212725](https://user-images.githubusercontent.com/36408599/225189432-35736a15-ef7f-46f8-b9f0-cd2be3b7aaec.png)
Also, I'm very sorry for what happened in your server a few months ago.  I've been better about behaving myself lately so can you please not only fix this issue but also unban me from your server?  I apologized to ElChicoEevee on Twitter as well as he seemed to be the most offended.  I promise that if you were to let me back in that I would not only behave, but also make meaningful contributions to the research.  Maybe even help fix the bug causing this error.

**Comment by melsbacksfriend** [comment]
I also tried apologizing to mv but couldn't as I was blocked.

**Comment by melsbacksfriend** [comment]
nvm just had a bad dump.  redumped and works as expected.  an unban would still be nice tho.

**Comment by trains193** [comment]
Hi sorry to disturb you but I wish that you van do an "EVEE" compatible with pokemon Scarlett ans violet 
Tank you
