### ISSUE TITLE
Problem exporting message files

### ISSUE THREAD

**Issue by Digote** [pkZukan/gftool#15]
I'm trying to export the text files with the new DLC, but it seems to be having some issues. It should be exporting one .dat and one .tbl, but it's only exporting .tbl for some files.

Congratulations on the project! Without it, I wouldn't be able to make the port to my language.

Script
![script](https://github.com/pkZukan/gftool/assets/45742711/e4e48b4e-1b75-47b0-9dcf-b6b19e49e11c)

Common
![common](https://github.com/pkZukan/gftool/assets/45742711/fbc80c29-64b0-455a-8597-58d3a66755eb)

**Comment by Reisyukaku** [comment]
Thanks! This seems to be missing hashes from the `hashes_inside_fd.txt`. Updated hashes will be pushed here once cracked.
https://github.com/pkZukan/PokeDocs/tree/main/SV/Hashlists/FileSystem

**Comment by Digote** [comment]
I did another dump with a new 'hashees_inside' that was provided to me on the PokeModding Discord. The number of files has increased, and it seems to be correct now. I also tested it with PKnx, and the text is now in the file.

Thanks for your help.

![image](https://github.com/pkZukan/gftool/assets/45742711/22514f9e-3d24-41ac-a1db-3b1bce0af25a)

![image](https://github.com/pkZukan/gftool/assets/45742711/acb789e0-cabf-4df6-8b82-2e5a766ac42d)

**Comment by tomxhachijuroku** [comment]
How did you make it work with PKnx?
I got the latest version dumped the game with nxdumptool, but I'm getting an error:
![Bez tytułu](https://github.com/pkZukan/gftool/assets/64981865/9e39bc88-bd90-4e65-9fca-2771a452c31a)

**Comment by tomxhachijuroku** [comment]
But I got the error opening a clean dump, not modded, with "data.trpfd" and "data.trpfs" inside the "arc" folder. I mean how did you opened the files inside "message" folder all I care about from PKnx is the dialog editing for my translation project, do you have a way to use PKnx to open just the "common" and "script" .dat files, right now I'm using "xytext.exe" but its old and doesn't make you import the .txt file back and does not display the files names just numbers, and like PKnx i doesn't save pasted text, if you don't pres space or enter, with is annoying wish someone would fix that, hours of translation sometimes lost because of this, please answer, thanks.

**Comment by Reisyukaku** [comment]
I havent used PKNX, seems like a question for them.

**Comment by tomxhachijuroku** [comment]
> I havent used PKNX, seems like a question for them.

Oh, sorry I just realized that [Digote](https://github.com/Digote), not you used PKnx, sorry.

**Comment by tomxhachijuroku** [comment]
> I did another dump with a new 'hashees_inside' that was provided to me on the PokeModding Discord. The number of files has increased, and it seems to be correct now. I also tested it with PKnx, and the text is now in the file.
> 
> Thanks for your help.
> 
> ![image](https://user-images.githubusercontent.com/45742711/269012038-22514f9e-3d24-41ac-a1db-3b1bce0af25a.png)
> 
> ![image](https://user-images.githubusercontent.com/45742711/269012074-acb789e0-cabf-4df6-8b82-2e5a766ac42d.png)

Tell me please how did you made it work with PKnx, se my posts above why, thank you.

**Comment by Digote** [comment]
Contact me on discord.
I'm on the PokeModding server
![#help-and-tech-support  PokeModding - Discord](https://github.com/pkZukan/gftool/assets/45742711/de726178-5150-4e37-a1b2-e6507579fbd8)

**Comment by tomxhachijuroku** [comment]
> Contact me on discord. I'm on the PokeModding server ![#help-and-tech-support PokeModding - Discord](https://user-images.githubusercontent.com/45742711/272705005-de726178-5150-4e37-a1b2-e6507579fbd8.jpg)

Cant' find PokeModding, only got Pokemod, and can't find @Digote too.
