### ISSUE TITLE
Update for the teal mask DLC?

### ISSUE THREAD

**Issue by tomxhachijuroku** [pkZukan/gftool#16]
Hello, I think the Tree View, needs to be updated to include new files added in the 2.0.1 update, like in "appli\data".
I can't find most of the new graphic to edit. The only ones I found where in:
common_gym
dressup
pokedex
status
tips
tokkun
Folders, because some .arc files inside those folders where updated with new graphics, so I concluded that the rest must be in some new folders not visible in the current 1.0.3 version, or am I wrong, please answer.

**Comment by Reisyukaku** [comment]
Tree view is auto generated from the trpfs/trpfd. Are you using latest hashes?

**Comment by tomxhachijuroku** [comment]
OK, how to update the hashes?
I've putted the "hashes_inside_fd.txt" and "hashes_inside_trpak.txt" files inside the folder with TrinityModLoader.exe and nothing, and Help only has a About option no Help > Get Latest Hashes?

**Comment by Terasol** [comment]
please use the latest nightly build, as the latest release version does not have the function to update the Hashes:
https://github.com/pkZukan/gftool/releases/tag/nightly

**Comment by tomxhachijuroku** [comment]
Thanks it works now.
Is the GFPAKHashCache.bin file important? Because it asks me every time I open the program, but it doesn't hinder from using the software, and I couldn't find it in the internet, where to get it?

**Comment by Reisyukaku** [comment]
its a madeup format that we made to store hashes. It should be setup to use either that or the txt with hashes, but the txt should take precedence.

**Comment by tomxhachijuroku** [comment]
OK I've made a empty GFPAKHashCache.bin file and it stopped asking, thanks and have a wonderful time, bye.
