### ISSUE TITLE
Liboodle.dll file missing

### ISSUE THREAD

**Issue by Musest142** [pkZukan/gftool#22]
I am trying to use the Pokemon Compass mod, but I can't even figure out how to get the mod loader to even work properly.

I get an error that says "Liboodle.dll file is missing. Exporting from TRPFS is disabled"

the loader then opens up normally but it doesn't work on the romfs folder, or at least I can't actually apply the mod. What do I do?
Also, I did redownload the mod loader and checked the files and such, I found nothing to do with this file

![image_2024-10-11_165025789](https://github.com/user-attachments/assets/85843f3d-b916-4f2d-8789-d7b0d129fa17)

**Comment by Reisyukaku** [comment]
Per the README,
`Trinity Mod Loader requires the oo2core_8_win64.dll and an up-to-date GFPAKHashCache.bin.`

In the future we will be seperating tools though so this wont be a requirement

**Comment by Musest142** [comment]
thanks
