### ISSUE TITLE
System Argument Out of Range Error

### ISSUE THREAD

**Issue by Grip555** [pkZukan/gftool#8]
I keep on getting this error when I move mods up and down the load order. I'm trying to prioritise specific mods, but I can't do that easily without being able to shift mods in the load order.

[Crash Log.txt](https://github.com/pkZukan/gftool/files/10254844/Crash.Log.txt)

**Comment by Vikijaka** [comment]
Do we need a specific version of DotNet 6? i just grabbed the latest one from https://dotnet.microsoft.com/en-us/download  
v6 indeed ~ 6.0.16 to be specific

Downloaded latest release of TML
C&P and renamed from Warframe next to TML.exe  -> oo2core_9_win64.dll to oo2core_8_win64.dll
startet TML.exe
"Couldnt find trpfs/trpfd" (which should be normal
TML UI -> cliking anywhere; e.g. Add Mod or empty space above it -> error ^

https://pastebin.com/EVeS99q4
