### ISSUE TITLE
doesn't detect .net installation

### ISSUE THREAD

**Issue by d3aths** [pkZukan/gftool#9]
ive just installed the .net 6.0.12 full sdk which includes the windows desktop app. wouldn't detect it when i try to open the exe. the folder i put it on was with my emulator which is on an external ssd so thought that might be the problem but installing it to my c drive still doesn't work. even uninstalled and went to the 6.0.0 version (which the popup was saying it needed), but it still tried to tell me i don't have .net installed?

**Comment by Reisyukaku** [comment]
Quite the windows moment. Not sure, the .net 6.0 runtime should be enough though. This issue isnt exactly in scope of the project though either. 

https://github.com/pkZukan/gftool/blob/main/TrinityModLoader/TrinityModLoader.csproj#L5
